# Generated by Django 3.2.13 on 2022-11-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='glade',
            new_name='grade',
        ),
    ]
