# Generated by Django 3.2.13 on 2022-11-02 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_like_user'),
        ('posts', '0003_post_user'),
    ]

    operations = [
    ]
